// export const mockBurnedCards: IUserCartItems = {
//   cartId: "cl7ls1l3x01270mzl8eejqhfo",
//   count: 8,
//   totalPrice: 126357,
//   cards: [
//     {
//       id: "20220729C182",
//       createdAt: "2022-07-29T10:09:02.730Z",
//       updatedAt: "2022-09-11T09:25:41.093Z",
//       itemName: "sdasddffawq321231",
//       frontImage: "https://api-dev-collectorcrypt.herokuapp.com/1659089342176.png",
//       backImage: "https://api-dev-collectorcrypt.herokuapp.com/1659089342583.png",
//       type: "Card",
//       category: "Hockey",
//       year: "1992",
//       serial: "123123",
//       insuredValue: "3234",
//       autographed: true,
//       author: {
//         id: "1",
//         name: "name",
//         wallet: "wallet",
//       },
//       status: "Minted",
//       vault: "PWCC",
//       location: "7560 SW Durham Rd Tigard, OR 97224",
//       vaultId: "",
//       gradingCompany: "Beckett",
//       grade: "7.5–Near Mint +",
//       qualifiers: [],
//       authenticated: true,
//       centering: "",
//       corners: "",
//       surface: "",
//       edges: "",
//       submissionID: "123123123",
//       gradingID: "",
//       gradeNum: "12",
//       ReasonForRejection: null,
//       suggestPrice: "12",
//       nftStatus: "Valid",
//       nftAddress: "HDUmtbhsXCGogT3aVSDXWa7Kdob63BNYbw3EZ51doWsQ",
//       authorId: "cl59g1hsh00001cu3tutjq5zp",
//       shippingId: "20220729S134",
//       outboundShipmentId: null,
//       cartId: "cl7ls1l3x01270mzl8eejqhfo",
//       burnId: null,
//       owner: { wallet: "BaAQb8TSnikUUMbbiq6smV431qw616VU7CQW7ES1S6sH" },
//       ownerId: "",
//       UserCards: {
//         user: {
//           wallet: "12321",
//         },
//       },
//     },
//     // {
//     //   explorerURL:
//     //     "https://explorer.solana.com/address/7wGqCBDNov3pDJgP1Hb1hDSY4Vkb8AsVGf5tRdzCo2d?cluster=devnet",
//     //   solscanURL:
//     //     "https://solscan.io/address/7wGqCBDNov3pDJgP1Hb1hDSY4Vkb8AsVGf5tRdzCo2d?cluster=devnet",
//     //   address: "7wGqCBDNov3pDJgP1Hb1hDSY4Vkb8AsVGf5tRdzCo2d",
//     //   owner: "BaAQb8TSnikUUMbbiq6smV431qw616VU7CQW7ES1S6sH",
//     //   collectorID: "20220809C221",
//     //   serialNumber: 12312312,
//     //   type: "Card",
//     //   category: "Football",
//     //   status: "Valid",
//     //   year: "2000",
//     //   insuredValue: 123123,
//     //   vault: "PWCC",
//     //   location: "7560 SW Durham Rd Tigard, OR 97224",
//     //   vaultID: "1231231",
//     //   submissionID: "345345",
//     //   gradingID: "12311321",
//     //   gradingCompany: "Beckett",
//     //   autographed: true,
//     //   theGrade: "7.5–Near Mint +",
//     //   centering: "qadwe123",
//     //   corners: "123wdawd",
//     //   edges: "adw1231",
//     //   qualifiers: ["OC - Off Center", "ST - Staining"],
//     //   surface: "ad132123",
//     //   authenticated: true,
//     //   aversImage: "https://arweave.net/U8qEx4rF5uYnlHAGPhMzD7VegJvjtA7180HXfXKGkmU",
//     //   reversImage: "https://arweave.net/U8tXpvLWHWW0-Mv3alxMkf7muxhe6iUCl5t3gkqCfzo",
//     //   sellerFeeBasisPoints: 50,
//     //   externalURL:
//     //     "https://dev.collectorcrypt.com/assets/solana/7wGqCBDNov3pDJgP1Hb1hDSY4Vkb8AsVGf5tRdzCo2d",
//     //   collectionName: "Collector",
//     //   collectionFamily: "COLLECTOR",
//     //   nameShort: "awdsad12312",
//     //   name: "awdsad12312",
//     //   symbol: "pNFT",
//     //   contractAddress: "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
//     //   tokenID: "4213421321324123sad",
//     //   blockchain: "Solana",
//     // },
//     // {
//     //   explorerURL:
//     //     "https://explorer.solana.com/address/EZ92yoVHTxxN2Ze3JodNC5NCsjF7r6jySE9QWEWRq5Js?cluster=devnet",
//     //   solscanURL:
//     //     "https://solscan.io/address/EZ92yoVHTxxN2Ze3JodNC5NCsjF7r6jySE9QWEWRq5Js?cluster=devnet",
//     //   address: "EZ92yoVHTxxN2Ze3JodNC5NCsjF7r6jySE9QWEWRq5Js",
//     //   collectionName: "Collector",
//     //   collectionFamily: "COLLECTOR",
//     //   owner: "BaAQb8TSnikUUMbbiq6smV431qw616VU7CQW7ES1S6sH",
//     //   collectorID: "20220706C6",
//     //   serialNumber: 245267,
//     //   type: "Card",
//     //   category: "Baseball",
//     //   status: "Valid",
//     //   year: "1988",
//     //   insuredValue: 0,
//     //   vault: "PWCC",
//     //   location: "7560 SW Durham Rd Tigard, OR 97224",
//     //   vaultID: "1342",
//     //   submissionID: null,
//     //   gradingID: null,
//     //   autographed: true,
//     //   theGrade: "NM/Mint+ 8.5",
//     //   centering: "4",
//     //   corners: "3",
//     //   edges: "3",
//     //   qualifiers: ["B"],
//     //   surface: "2",
//     //   authenticated: true,
//     //   aversImage: "https://arweave.net/1MBZNROTjpHy3oVGdgE8rO6sZhPJFIDXuXAl3ojn4eM",
//     //   reversImage: "https://arweave.net/G3OtZE9H2xcsvHyHEktdXcY9mM540a3HABJZqy3h8jw",
//     //   sellerFeeBasisPoints: 50,
//     //   description: "A description about my custom pNFT",
//     //   externalURL:
//     //     "https://dev.collectorcrypt.com/assets/solana/EZ92yoVHTxxN2Ze3JodNC5NCsjF7r6jySE9QWEWRq5Js",
//     //   nameShort: "Baseball Vol.211",
//     //   name: "A description about my custom pNFT",
//     //   symbol: "COLLECTOR",
//     //   contractAddress: "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
//     //   tokenID: "4213421321324123sad",
//     //   blockchain: "Solana",
//     // },
//     // {
//     //   explorerURL:
//     //     "https://explorer.solana.com/address/53bEV5uz32iF98ZugJDcRfn3WXDwQXTzYj3ZG2fJjr7v?cluster=devnet",
//     //   solscanURL:
//     //     "https://solscan.io/address/53bEV5uz32iF98ZugJDcRfn3WXDwQXTzYj3ZG2fJjr7v?cluster=devnet",
//     //   address: "53bEV5uz32iF98ZugJDcRfn3WXDwQXTzYj3ZG2fJjr7v",
//     //   owner: "BaAQb8TSnikUUMbbiq6smV431qw616VU7CQW7ES1S6sH",
//     //   collectorID: "20220809C220",
//     //   serialNumber: 123123,
//     //   type: "Card",
//     //   category: "Hockey",
//     //   status: "Valid",
//     //   year: "2000",
//     //   insuredValue: 123,
//     //   vault: "PWCC",
//     //   location: "7560 SW Durham Rd Tigard, OR 97224",
//     //   vaultID: "1123123",
//     //   submissionID: "123",
//     //   gradingID: "NaN",
//     //   gradingCompany: "Beckett",
//     //   autographed: false,
//     //   theGrade: "6–EX-NM",
//     //   centering: "",
//     //   corners: "",
//     //   edges: "",
//     //   qualifiers: ["MC - Miscut", "OC - Off Center"],
//     //   surface: "",
//     //   authenticated: false,
//     //   aversImage: "https://arweave.net/U8qEx4rF5uYnlHAGPhMzD7VegJvjtA7180HXfXKGkmU",
//     //   reversImage: "https://arweave.net/U8tXpvLWHWW0-Mv3alxMkf7muxhe6iUCl5t3gkqCfzo",
//     //   sellerFeeBasisPoints: 50,
//     //   externalURL:
//     //     "https://dev.collectorcrypt.com/assets/solana/53bEV5uz32iF98ZugJDcRfn3WXDwQXTzYj3ZG2fJjr7v",
//     //   collectionName: "Collector",
//     //   collectionFamily: "COLLECTOR",
//     //   nameShort: "awdawe13212ew",
//     //   name: "awdawe13212ew",
//     //   symbol: "pNFT",
//     //   contractAddress: "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
//     //   tokenID: "4213421321324123sad",
//     //   blockchain: "Solana",
//     // },
//     // {
//     //   explorerURL:
//     //     "https://explorer.solana.com/address/75zLKY7aKXXRfTzdvYf9hrqDRhdxn5rkiFNwhwsiVk8X?cluster=devnet",
//     //   solscanURL:
//     //     "https://solscan.io/address/75zLKY7aKXXRfTzdvYf9hrqDRhdxn5rkiFNwhwsiVk8X?cluster=devnet",
//     //   address: "75zLKY7aKXXRfTzdvYf9hrqDRhdxn5rkiFNwhwsiVk8X",
//     //   owner: "BaAQb8TSnikUUMbbiq6smV431qw616VU7CQW7ES1S6sH",
//     //   collectorID: "2022081914C341",
//     //   serialNumber: 0,
//     //   type: "Card",
//     //   category: "Hockey",
//     //   status: "Valid",
//     //   year: "2000",
//     //   insuredValue: 12,
//     //   vault: "PWCC",
//     //   location: "7560 SW Durham Rd Tigard, OR 97224",
//     //   vaultID: "64563453432",
//     //   submissionID: "123123",
//     //   gradingID: "",
//     //   gradingCompany: "TradingCardsSGC",
//     //   autographed: false,
//     //   theGrade: "NM/Mint 8",
//     //   centering: "",
//     //   corners: "",
//     //   edges: "",
//     //   qualifiers: "",
//     //   surface: "",
//     //   authenticated: false,
//     //   aversImage: "https://arweave.net/9Te5Km0BaSaeLzp5WXo_tww-11bbvWqoPGbrhJ3Ko7w",
//     //   reversImage: "https://arweave.net/Ik9lwR_6joJr0-udKWGRNMGX6hcnUL4H0rsdxIbPDH0",
//     //   sellerFeeBasisPoints: 50,
//     //   externalURL:
//     //     "https://dev.collectorcrypt.com/assets/solana/75zLKY7aKXXRfTzdvYf9hrqDRhdxn5rkiFNwhwsiVk8X",
//     //   collectionName: "Collector",
//     //   collectionFamily: "COLLECTOR",
//     //   nameShort: "sfw34234234",
//     //   name: "sfw34234234",
//     //   symbol: "pNFT",
//     //   contractAddress: "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
//     //   tokenID: "4213421321324123sad",
//     //   blockchain: "Solana",
//     // },
//     // {
//     //   explorerURL:
//     //     "https://explorer.solana.com/address/Fk7NYUzSJXKuJgdVmaofFav9DJHjJ1vRWHWB2Mrxbwgz?cluster=devnet",
//     //   solscanURL:
//     //     "https://solscan.io/address/Fk7NYUzSJXKuJgdVmaofFav9DJHjJ1vRWHWB2Mrxbwgz?cluster=devnet",
//     //   address: "Fk7NYUzSJXKuJgdVmaofFav9DJHjJ1vRWHWB2Mrxbwgz",
//     //   owner: "BaAQb8TSnikUUMbbiq6smV431qw616VU7CQW7ES1S6sH",
//     //   collectorID: "20220809C232",
//     //   serialNumber: 1231231231231231,
//     //   type: "Card",
//     //   category: "BoxingAndMMA",
//     //   status: "Valid",
//     //   year: "2000",
//     //   insuredValue: 12321,
//     //   vault: "PWCC",
//     //   location: "7560 SW Durham Rd Tigard, OR 97224",
//     //   vaultID: "123123123",
//     //   submissionID: "123123",
//     //   gradingID: "",
//     //   gradingCompany: "Beckett",
//     //   autographed: false,
//     //   theGrade: "4.5 VG-EX+",
//     //   centering: "",
//     //   corners: "",
//     //   edges: "",
//     //   qualifiers: "",
//     //   surface: "",
//     //   authenticated: false,
//     //   aversImage: "https://arweave.net/U8qEx4rF5uYnlHAGPhMzD7VegJvjtA7180HXfXKGkmU",
//     //   reversImage: "https://arweave.net/U8tXpvLWHWW0-Mv3alxMkf7muxhe6iUCl5t3gkqCfzo",
//     //   sellerFeeBasisPoints: 50,
//     //   externalURL:
//     //     "https://dev.collectorcrypt.com/assets/solana/Fk7NYUzSJXKuJgdVmaofFav9DJHjJ1vRWHWB2Mrxbwgz",
//     //   collectionName: "Collector",
//     //   collectionFamily: "COLLECTOR",
//     //   nameShort: "фвЙЦФв123у",
//     //   name: "фвЙЦФв123у",
//     //   symbol: "pNFT",
//     //   contractAddress: "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
//     //   tokenID: "4213421321324123sad",
//     //   blockchain: "Solana",
//     // },
//     // {
//     //   explorerURL:
//     //     "https://explorer.solana.com/address/7o5FEPm2j1Nos8nUpKmM4SMDALCs4Kabd5NhyqesZ34m?cluster=devnet",
//     //   solscanURL:
//     //     "https://solscan.io/address/7o5FEPm2j1Nos8nUpKmM4SMDALCs4Kabd5NhyqesZ34m?cluster=devnet",
//     //   address: "7o5FEPm2j1Nos8nUpKmM4SMDALCs4Kabd5NhyqesZ34m",
//     //   owner: "BaAQb8TSnikUUMbbiq6smV431qw616VU7CQW7ES1S6sH",
//     //   collectorID: "20220809C224",
//     //   serialNumber: 123123123123,
//     //   type: "Card",
//     //   category: "Hockey",
//     //   status: "Valid",
//     //   year: "2000",
//     //   insuredValue: 12312,
//     //   vault: "PWCC",
//     //   location: "7560 SW Durham Rd Tigard, OR 97224",
//     //   vaultID: "123123",
//     //   submissionID: "123123",
//     //   gradingID: "",
//     //   gradingCompany: "PSAorDNA",
//     //   autographed: false,
//     //   theGrade: "Good 2",
//     //   centering: "",
//     //   corners: "",
//     //   edges: "",
//     //   qualifiers: ["MC - Miscut", "OC - Off Center", "ST - Staining"],
//     //   surface: "",
//     //   authenticated: false,
//     //   aversImage: "https://arweave.net/U8qEx4rF5uYnlHAGPhMzD7VegJvjtA7180HXfXKGkmU",
//     //   reversImage: "https://arweave.net/U8tXpvLWHWW0-Mv3alxMkf7muxhe6iUCl5t3gkqCfzo",
//     //   sellerFeeBasisPoints: 50,
//     //   externalURL:
//     //     "https://dev.collectorcrypt.com/assets/solana/7o5FEPm2j1Nos8nUpKmM4SMDALCs4Kabd5NhyqesZ34m",
//     //   collectionName: "Collector",
//     //   collectionFamily: "COLLECTOR",
//     //   nameShort: "ADCFD123Q2",
//     //   name: "ADCFD123Q2",
//     //   symbol: "pNFT",
//     //   contractAddress: "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
//     //   tokenID: "4213421321324123sad",
//     //   blockchain: "Solana",
//     // },
//   ],
// };
export {};
